# Generated by Django 2.1.7 on 2019-03-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_pk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
