# Generated by Django 2.1.7 on 2019-03-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_post_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
